In [16]:
import numpy as np

<h3> The Basics</h3>

In [ ]:
a = np.array([1,2,3])
print (a)

# The correct syntax of 2-D array in numpy is 
# b=np.array([[row_1],[row_2])
b = np.array([[1,2,3],[4,5,6]])
print(b)

In [28]:
# Get Dimension of an array
print(a.ndim) # 1 - since it is a 1-D array
print(b.ndim) # 2 - since it is a 2-D array

# Get shape of an array
print(a.shape) # (3,) - since it has three elements in a 1-D array
print(b.shape) # (2,3) - 2 rows and three columns

#Get data type of an array
print(a.dtype)
print(b.dtype)



1
2
(3,)
(2, 3)
int64
int64


<h3>Accessing / Changing specific elements of rows and columns</h3>

In [64]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print('Shape of a', a.shape) # 2 rows and 7 columns

# Access a specific element
print(a[1,5]) # 13
#OR
print(a[1,-2])

# Get a specific row
print(a[0,:])
# Get a specific Column 
print(a[:,1])

# Get 2,4,6 from row 0
print(a[0,1:6:2])

# Changing of elements 
a[1,-1]=41
print(a)

# Change all rows and second column to 5
a[:,1]=5
print(a)

# EXAMPLE
dummy = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(dummy)

dummy.shape

# To access the element 4
print(dummy[0,1,1])

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
Shape of a (2, 7)
13
13
[1 2 3 4 5 6 7]
[2 9]
[2 4 6]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 41]]
[[ 1  5  3  4  5  6  7]
 [ 8  5 10 11 12 13 41]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4


<h3>Initializing different types of array</h3>

In [102]:
# ALL 0'S MATRIX
q=np.zeros(6)
w=np.zeros(6, dtype='int32')
e=np.zeros((2,3))
print(q)
print(w)
print(e)

# ALL 1'S MATRIX
r= np.ones(3, dtype='int32')
print(r)

# ANY OTHER NUMBER
f=np.full((2,2),99)
print(f)

# RANDOM DECIMAL NUMBER
v = np.random.rand(4,2)
print(v)

# RANDOM INTEGER NUMBER
y= np.random.randint(9)
print(y)

z= np.random.randint(4,7,size=(3,3))
print(z)

# IDENTITY MATRIX
g= np.identity(3, dtype='int32')
print(g)

# REPEATING THE ARRAY 
arr = np.array([[1,2,3]]) # 2-D array
rep = np.repeat(arr,3,axis=0) # along the rows
rep_1 = np.repeat(arr,3,axis=1) # along the columns
print(rep)
print(rep_1)

[0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0]
[[0. 0. 0.]
 [0. 0. 0.]]
[1 1 1]
[[99 99]
 [99 99]]
[[0.80502715 0.40883446]
 [0.52476542 0.94352262]
 [0.51244258 0.14724816]
 [0.65685628 0.41319569]]
4
[[5 5 6]
 [5 4 4]
 [5 6 4]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


<h3>SOLVE THIS PROBLEM</h3>


INITIALIZE THIS ARRAY WITHOUT MANUALLY TYPING IT
1 1 1 1 1
1 0 0 0 1
1 0 9 0 1
1 0 0 0 1
1 1 1 1 1


In [133]:
s1 = np.ones((5,5), dtype='int32')

s2= np.zeros((3,3),dtype='int32')
print(s1)
print(s2)

s2[1,1]=9
print(s2)

s1[1:4,1:4]=s2
print(s1)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


<h3>Mathematics</h3>

In [154]:
a=np.array([1,2,3,4,5])
print(a)

#SUM
print(a+2)

#SUBTRACT
print(a-2)

#MULTIPLY 
print(a*6)

#DIVIDE
print(a/2)

b=np.array([1,0,1,1,0])
print(b+a)

# MATRIX MULTIPLICATION
a1=np.ones((2,3),dtype='int32')
a2=np.full((3,2),2, dtype='int32')
print(a1)
print(a2)
b1=np.matmul(a1,a2)
print(b1)

# FIND THE DETERMINANT
x=np.identity(3)
print(np.linalg.det(x))

# WE CAN ALSO FIND INVERSE OF MATRIX, EIGEN VALUES , SVD, ETC

# MIN , MAX , SUM OF ARRAY
z=np.array([[1,2,3,4],[5,6,7,8]])
print(np.min(z))
print(np.max(z))
print(np.sum(z))

[1 2 3 4 5]
[3 4 5 6 7]
[-1  0  1  2  3]
[ 6 12 18 24 30]
[0.5 1.  1.5 2.  2.5]
[2 2 4 5 5]
[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]
[[6 6]
 [6 6]]
1.0
1
8
36


<h3>Reorganizing and stacking of an array</h3>

In [160]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)
after=before.reshape(4,2)
print(after)
print(after.shape)

(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


In [162]:
# VERTICALLY STAKCING ARRAY 

v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
print(np.stack([v1,v1,v2,v2]))

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


<h3>Solve a few Questions</h3>

The Matrix is 
1   2   3   4   5
6   7   8   9   10
11  12  13  14  15
16  17  18  19  20
21  22  23  24  25
26  27  28  29  30

In [167]:
prac = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(prac)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [169]:
# ACCESS ELEMENTS 11,12,16,17
print(prac[2:4,0:2])

[[11 12]
 [16 17]]


In [177]:
# ACCESS ELEMENT 2,8,14,20
print(prac[[0,1,2,3],[1,2,3,4]])

[ 2  8 14 20]


In [183]:
# ACCESS ELEMENT 4,5, 24,25,29,30
print(prac[[0,4,5],3:])

[[ 4  5]
 [24 25]
 [29 30]]
